CREATE TABLE MARKET_USER(
	USER_NO     NUMBER CONSTRAINT MARKET_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN MARKET_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN MARKET_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN MARKET_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN MARKET_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN MARKET_USER.ENROLL_DATE IS '사용자 가입일';

CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO MARKET_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO MARKET_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT * FROM MARKET_USER;



-----------------------------------------------------------------------



CREATE TABLE MARKET_PRODUCT(
	PRODUCT_NO     NUMBER CONSTRAINT MARKET_USER_PK PRIMARY KEY,
	PRODUCT_NAME   VARCHAR2(30) NOT NULL,
	PRODUCT_PICE   NUMBER NOT NULL,
	PRODUCT_STOCK  NUMBER NOT NULL,
);

COMMENT ON COLUMN MARKET_PRODUCT.PRODUCT_NO     IS '상품 번호';
COMMENT ON COLUMN MARKET_PRODUCT.PRODUCT_NAME   IS '상품 이름';
COMMENT ON COLUMN MARKET_PRODUCT.PRODUCT_PICE   IS '상품 가격';
COMMENT ON COLUMN MARKET_PRODUCT.PRODUCT_STOCK  IS '상품 재고';

CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO MARKET_PRODUCT 
VALUES(SEQ_USER_NO.NEXTVAL, '사과', 1000, 3);
INSERT INTO MARKET_USER 
VALUES(SEQ_USER_NO.NEXTVAL, '바나나', 2000, 5);

SELECT * FROM MARKET_PRODUCT;